fix: client EIO
size - offset is not right and it may cause "thread
'tokio-runtime-worker' panicked at 'attempt to subtract with overflow',
src/server/rpc/user.rs:62:31"